# Generated by Django 4.2.7 on 2023-11-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, unique=True)),
                ('category_slug', models.SlugField(max_length=200, unique=True)),
                ('category_description', models.TextField(blank=True)),
                ('category_image', models.ImageField(upload_to='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True)),
                ('product_slug', models.SlugField(max_length=200, unique=True)),
                ('product_price', models.PositiveIntegerField()),
                ('product_description', models.TextField(blank=True, default=None)),
                ('stock_quantity', models.PositiveBigIntegerField()),
                ('stock_unit', models.CharField(choices=[('kg', 'Kilogram'), ('lbs', 'Lbs'), ('piece', 'Piece')], default='piece', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
